#!/bin/bash
# Get the dir of this project
DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/..
if [[ $# -lt 1 ]]; then echo "usage: run [-Djava.prop=value...] className (eg. bril.test.JsonToJsonTest) [args...]"; exit 1; fi
java -cp "$DIR/target/scala-2.13/bril-scala-assembly-0.1.0.jar" "$@"